name: Build & Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout code"
        uses: actions/checkout@v1
      - name: "Setup Environment"
        run: pip install -r mkdocs.requirements

      - name: "Build mkdocs"
        run: mkdocs build

      - name: "Save build artifact"
        uses: actions/upload-pages-artifact@v1.0.8
        with:
          path: ${{ github.workspace }}/bin

  deploy:
    needs: build

    permissions:
      pages: write
      id-token: write

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    runs-on: ubuntu-latest
    steps:
      - name: "Deploy to GitHub Pages"
        id: deployment
        uses: actions/deploy-pages@v1.0.6
